services:
    db:
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: invoice_api
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U user -d invoice_api']
            interval: 5s
            timeout: 5s
            retries: 5
        restart: always

    backend:
        build:
            context: .
            dockerfile: Dockerfile
            target: runtime
        depends_on:
            db:
                condition: service_healthy
        environment:
            NODE_ENV: production
            DATABASE_URL: postgres://user:password@db:5432/invoice_api
            JWT_SECRET: secret_key123
            PORT: 3000
        expose:
            - '3000'
        restart: always

    nginx:
        image: nginx:1.27-alpine
        depends_on:
            - backend
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        restart: always

volumes:
    db_data:
